"""Meal planning + recipe suggestions. Ingredients auto-flow to the grocery list.

Recipes are generated by Claude on-demand so we don't ship a hardcoded cookbook.
The agent can plan a week, swap a meal, or pull a single recipe.
"""
from __future__ import annotations

import json
from datetime import date, datetime, timedelta

from myassistant.core import family as fam
from myassistant.core.memory import db
from myassistant.core.registry import skill
from myassistant.skills.todo_lists import add_to_list


@skill(
    name="plan_meal",
    description=("Plan a meal on a given date. date=YYYY-MM-DD, slot=breakfast|lunch|dinner|snack, "
                 "title is the dish name. Recipe text and ingredients can be filled in later via "
                 "save_recipe. Replaces any existing meal in that slot/date."),
)
def plan_meal(date: str, title: str, slot: str = "dinner", notes: str = "") -> str:
    f = fam.get_or_create_default_family()
    with db() as s:
        existing = (
            s.query(fam.MealPlan)
            .filter(fam.MealPlan.family_id == f.id,
                    fam.MealPlan.date == date,
                    fam.MealPlan.slot == slot)
            .one_or_none()
        )
        if existing:
            existing.title = title
            existing.notes = notes
            mid = existing.id
        else:
            mp = fam.MealPlan(family_id=f.id, date=date, slot=slot, title=title, notes=notes)
            s.add(mp)
            s.flush()
            mid = mp.id
    return f"planned {slot} for {date}: {title} (#{mid})"


@skill(
    name="save_recipe",
    description=("Attach a full recipe + ingredients to an already-planned meal. "
                 "ingredients is a JSON-style list of objects like "
                 "[{'item': 'chicken thighs', 'qty': '2 lb'}, ...]."),
)
def save_recipe(meal_id: int, recipe: str, ingredients: list) -> str:
    with db() as s:
        mp = s.query(fam.MealPlan).filter(fam.MealPlan.id == meal_id).one_or_none()
        if not mp:
            return f"no meal #{meal_id}"
        mp.recipe = recipe
        normed = []
        for ing in ingredients or []:
            if isinstance(ing, dict):
                normed.append({"item": str(ing.get("item", "")), "qty": str(ing.get("qty", ""))})
            else:
                normed.append({"item": str(ing), "qty": ""})
        mp.ingredients_json = json.dumps(normed)
    return f"recipe saved on #{meal_id} ({len(normed)} ingredients)"


@skill(
    name="show_meal_plan",
    description="Show planned meals for the next N days (default 7).",
)
def show_meal_plan(days: int = 7) -> str:
    f = fam.get_or_create_default_family()
    today = date.today()
    end = today + timedelta(days=max(1, days))
    with db() as s:
        rows = (
            s.query(fam.MealPlan)
            .filter(fam.MealPlan.family_id == f.id,
                    fam.MealPlan.date >= today.isoformat(),
                    fam.MealPlan.date < end.isoformat())
            .order_by(fam.MealPlan.date, fam.MealPlan.slot)
            .all()
        )
        if not rows:
            return f"no meals planned for the next {days} days"
        by_date: dict[str, list] = {}
        for r in rows:
            by_date.setdefault(r.date, []).append(f"  {r.slot}: {r.title}")
        out = ["🍽️ Meal plan:"]
        for d in sorted(by_date.keys()):
            dt = datetime.fromisoformat(d)
            out.append(dt.strftime("%a %b %d"))
            out.extend(by_date[d])
        return "\n".join(out)


@skill(
    name="push_meal_ingredients_to_grocery",
    description=("Take the ingredients from one planned meal (by id) and append them "
                 "to the family grocery list. Returns how many were added."),
)
def push_meal_ingredients_to_grocery(meal_id: int, grocery_list_name: str = "Groceries") -> str:
    with db() as s:
        mp = s.query(fam.MealPlan).filter(fam.MealPlan.id == meal_id).one_or_none()
        if not mp:
            return f"no meal #{meal_id}"
        ings = json.loads(mp.ingredients_json or "[]")
    if not ings:
        return "no ingredients on that meal — call save_recipe first"
    items = [f"{i['qty']} {i['item']}".strip() for i in ings]
    return add_to_list(grocery_list_name, items, added_by=f"meal:{mp.title}", kind="grocery")


@skill(
    name="push_week_to_grocery",
    description=("Roll up ingredients from all planned meals in the next N days "
                 "(default 7) and append them to the grocery list. Great for Sunday prep."),
)
def push_week_to_grocery(days: int = 7, grocery_list_name: str = "Groceries") -> str:
    f = fam.get_or_create_default_family()
    today = date.today()
    end = today + timedelta(days=max(1, days))
    bucket: list[str] = []
    with db() as s:
        rows = (
            s.query(fam.MealPlan)
            .filter(fam.MealPlan.family_id == f.id,
                    fam.MealPlan.date >= today.isoformat(),
                    fam.MealPlan.date < end.isoformat())
            .all()
        )
        for mp in rows:
            for ing in json.loads(mp.ingredients_json or "[]"):
                bucket.append(f"{ing.get('qty','')} {ing.get('item','')}".strip())
    if not bucket:
        return "no ingredients found — plan meals + save recipes first"
    return add_to_list(grocery_list_name, bucket, added_by="weekly meal plan", kind="grocery")


@skill(
    name="tonights_dinner",
    description="Return tonight's planned dinner (title + recipe if present).",
)
def tonights_dinner() -> str:
    f = fam.get_or_create_default_family()
    today = date.today().isoformat()
    with db() as s:
        mp = (
            s.query(fam.MealPlan)
            .filter(fam.MealPlan.family_id == f.id,
                    fam.MealPlan.date == today,
                    fam.MealPlan.slot == "dinner")
            .one_or_none()
        )
        if not mp:
            return "no dinner planned for tonight"
        out = [f"Tonight: {mp.title}"]
        if mp.recipe:
            out.append("")
            out.append(mp.recipe)
        return "\n".join(out)
